### ISSUE TITLE
In epoch of COVID-19, we could develop this to help people around the world.

### ISSUE THREAD

**Issue by julioflima** [rocketseat-education/semana-omnistack-11#5]
I don't know what, but it's an idea. 

What is relevant to people overcome this?

I don't know, if this is the best place to talk about that. Fell free to moderate.

**Comment by ribeiroevandro** [comment]
I'm already working on a version that will be released soon. I rewrote the entire project, the API that was initially developed with Express, was migrated to AdonisJS and the Front End of the web application, is being written with NextJS, for the database, I'm using Postgres.

**Comment by juloko** [comment]
Cool, you gona open the project?

**Comment by JoeCarlos** [comment]
It's so cool, my friend. Can you open the project to colaboration?

**Comment by jpedroschmitz** [comment]
Hey guys, I think it's a great initiative!

You can for sure use this project and improve it by adding more features.

I'm going to close this issue, but feel free to share projects that you have been working on 💜
